version: 2
orbs:
  aws-cli: circleci/aws-cli@2.0.19
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Update apt to update
          command: sudo apt update
      - run:
          name: install wget to downlaod the files from internet
          command: sudo apt install wget zip unzip
      - run:
          name: Install aws cli
          command: sudo pip install awscli
      - run:
          name: Download packer 1.5.6
          command: wget -q https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip
      - run:
          name: Unzip packer
          command: unzip packer_1.5.6_linux_amd64.zip
      - run:
          name: Validate Packer Template
          command: ./packer validate ami.json
      - run:
          name: Build AMI
          command: ./packer build ami.json
workflows:
  version: 2
  build-ami:
    jobs:
    - build

